### ISSUE TITLE
[BUG] Turn off light automatically less than a minute

### ISSUE THREAD

**Issue by r-matsuzaka** [JnyJny/busylight#389]
### Description
I'm experiencing an issue with the BusyLight Python integration for my Kuando Omega device. The light turns off prematurely, staying on for only about 10 seconds instead of the intended 25 minutes.

### Environment
- Operating System: Ubuntu 20.04.6 LTS
- Python Version: 3.10.8
- BusyLight Model: Kuando Omega
- BusyLight Python Library: busylight-for-humans v0.32.0

### Code
Here's the relevant part of my code:

```python
def light_process():
    light = Light.first_light()
    light.on((0xff, 0, 0xff))
    sleep(25 * 60)  # 25 minutes
    light.off()
```

### Expected Behavior
The Kuando Omega light should turn on and stay on for 25 minutes before turning off.

### Actual Behavior
The light turns on but then turns off after about 10 seconds.

**Comment by JnyJny** [comment]
The [Kuando Busylight][https://github.com/JnyJny/busylight/blob/master/docs/devices/kuando.md#command-format] family requires a "keep alive" signal be sent to it approximately every 14 seconds. If the keep alive is received, the device keeps doing whatever it's doing. If 15 seconds goes by without a keep alive, the device stops executing whatever directives it was given.

This is a design "feature" of the device and is quite different behavior compared to other lights on the market. In order to keep that light on, you'll need to have a long lived process that sends the keep alive packet to the device. The `busylight.manager.LightManager` class will take care of sending the keep alive, you just need to have a process that runs for the duration.

Of all the lights supported, the Kuando lights are my least favorite to work with for precisely this reason.

**Comment by r-matsuzaka** [comment]
Hi, thank you very much for quick reply!
I appreciate your kindness about the characteristics of kuando products and the workaround.
I will try busylight.manager.LightManager.
Should I keep this issue open or close it?

**Comment by JnyJny** [comment]
You are welcome!

I was imprecise about how the keep alive is sent to the light. The `LightManager` class is how I collect all available lights and interact with them from the web API implemented by the `busyserve` command which utilizes `asyncio` to send commands to lights from a single long lived process without blocking. The `LightManager` class is also used in the command line interface implemented in `busylight.__main__` which is called from an async context:

````python
@cli.command(name="on")
def turn_lights_on(
    ctx: typer.Context,
    color: Optional[str] = typer.Argument(
        "green",
        callback=string_to_scaled_color,
        show_default=True,
    ),
) -> None:
    """Activate light."""
    logger.info("activating lights")
    try:
        manager.on(color, ctx.obj.lights, timeout=ctx.obj.timeout)
    except (KeyboardInterrupt, TimeoutError):
        manager.off(ctx.obj.lights)
    except NoLightsFound as error:
        typer.secho("No lights to turn on.", fg="red")
        raise typer.Exit() from None
```
If one of the lights is a Kuando device, the `manager.on` method will not return unless a timeout is specified or the process is interrupted from an externally generated signal (like the KeyboardInterrupt). So you'll need to spawn a process whose only job is to keep the light on for 25 minutes. In your code, you could do something like:

```
from busylight.manager import LightManager

manager = LightManager()
manager.on([0,255,0], timeout=25*60)
```

The `manager.on` method won't return for 25 minutes or it receives a signal but the keep alive is delivered every seven seconds via an asynchronous I/O task.

The web API found in `busylight.lights.api` also uses the `LightManager` class to perform operations on your lights.

You could start the server using the `busyserve` command and then use something like `requests` to command your lights indirectly thru the web API rather than directly via USB:

```python
import requests
from time import sleep

requests.get("http://localhost:8000/lights/on") # turns all lights on
sleep(25*60)
requests.get("http://localhost:8000/lights/off") # turns all lights off
```

Again, `LightManager` is supplying the asynchronous IO context that the Kuando light needs to ensure the keep alive packet is delivered at a constant cadence. 

I hope that's helpful, feel free to keep the thread open to ask questions or close it if you like.

**Comment by r-matsuzaka** [comment]
Oh, thank you so much for additional information!
This is very helpful.

I could do what I want to do. So I close this issue.
Thank you very much.
